CAStest/Models/IndividualEntrepreneur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CAStest.Models
{
    public class IndividualEntrepreneur: Individual
    {
    }
}

CAStest/Models/IndividualEntrepreneurViewModels/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CAStest.Models.IndividualEntrepreneurViewModels
{
    public class DetailsViewModel
    {
        public IndividualEntrepreneur IndividualEntrepreneur { get; set; }
        public List<Contact> Contacts { get; set; }
    }
}

CAStest/Models/IndividualsViewModel/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CAStest.Models.IndividualsViewModel
{
    public class DetailsViewModel
    {
        public Individual Individual { get; set; }
        public List<Contact> Contacts { get; set; }
    }
}

CAStest/Controllers/IndividualEntrepreneurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CAStest.Data;
using CAStest.Models;
using CAStest.Models.IndividualEntrepreneurViewModels;
using System.Globalization;
using System.Threading;

namespace CAStest.Controllers
{
    public class IndividualEntrepreneurController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IndividualEntrepreneurController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public async Task<IActionResult> Index()
        {
            if (User.Claims.FirstOrDefault(c => c.Value == "Admin") != null)
            {
                var entrepreneuer = _context.IndividualEntrepreneurs.Include(i => i.Company).ToList();
                return View(entrepreneuer);
            }
            else
            {
                var individualEntrepreneurs = _context.IndividualEntrepreneurs.Where(e => e.IsBlocked == false).Include(i => i.Company).ToList();
                return View(individualEntrepreneurs);
            }
        }

        public async Task<IActionResult> Cards()
        {
            if (User.Claims.FirstOrDefault(c => c.Value == "Admin") != null)
            {
                var entrepreneuer = _context.IndividualEntrepreneurs.Include(i => i.Company).ToList();
                return View(entrepreneuer);
            }
            else
            {
                var individualEntrepreneurs = _context.IndividualEntrepreneurs.Where(e => e.IsBlocked == false).Include(i => i.Company).ToList();
                return View(individualEntrepreneurs);
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var individualEntrepreneur = await _context.IndividualEntrepreneurs
                .Include(i => i.Company)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (individualEntrepreneur == null)
            {
                return NotFound();
            }
            DetailsViewModel model = new DetailsViewModel();
            model.IndividualEntrepreneur = individualEntrepreneur;
            model.Contacts = _context.Contacts.Include(c => c.ContactType).Where(c => c.CounterpartyId == id).ToList();
            return View(model);
        }
        
        public IActionResult Create()
        {
            var model = new CreateIEViewModel();
            model.Countries = new SelectList(Country.GetCountryList());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateIEViewModel model)
        {
            if (model != null)
            {
                IndividualEntrepreneur IE = new IndividualEntrepreneur()
                {
                    Address = model.Address,
                    DateOfBirth = model.DateOfBirth,
                    Fullname = model.Fullname,
                    Inn = model.Inn,
                    PassportData = model.PassportData,
                    Country = model.Country
                };
                _context.Individuals.Add(IE);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var individualEntrepreneur = await _context.IndividualEntrepreneurs.SingleOrDefaultAsync(m => m.Id == id);
            if (individualEntrepreneur == null)
            {
                return NotFound();
            }
            ViewData["Country"] = new SelectList(Country.GetCountryList());
            return View(individualEntrepreneur);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Fullname,Inn,DateOfBirth,PassportData,Address,Country,Id")] IndividualEntrepreneur individualEntrepreneur)
        {
            if (id != individualEntrepreneur.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(individualEntrepreneur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IndividualEntrepreneurExists(individualEntrepreneur.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = id });
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Discriminator", individualEntrepreneur.CompanyId);
            return View(individualEntrepreneur);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var individualEntrepreneur = await _context.IndividualEntrepreneurs
                .Include(i => i.Company)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (individualEntrepreneur == null)
            {
                return NotFound();
            }

            return View(individualEntrepreneur);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var individualEntrepreneur = await _context.IndividualEntrepreneurs.SingleOrDefaultAsync(m => m.Id == id);
            _context.IndividualEntrepreneurs.Remove(individualEntrepreneur);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IndividualEntrepreneurExists(int id)
        {
            return _context.IndividualEntrepreneurs.Any(e => e.Id == id);
        }

        public IActionResult Block(int id)
        {
            IndividualEntrepreneur individualEntrepreneur = _context.IndividualEntrepreneurs.FirstOrDefault(c => c.Id == id);
            individualEntrepreneur.IsBlocked = true;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult UnBlock(int id)
        {
            IndividualEntrepreneur individualEntrepreneur = _context.IndividualEntrepreneurs.FirstOrDefault(c => c.Id == id);
            individualEntrepreneur.IsBlocked = false;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CAStest/Views/IndividualEntrepreneur/Cards.cshtml
@model IEnumerable<CAStest.Models.IndividualEntrepreneur>

@{
    ViewData["Title"] = "Cards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width:100%; position:absolute; left:0px;">
    <h2 style="color:#066023; width:70%;" class="bigGreenCaption">Индивидуальные предприниматели</h2>
    <div class="controlPanel">
        <div class="buttonWrap">
            <div class='addingButton'><a title="Добавить физическое лицо" asp-action="Create"><img src='~/images/material/add.png' alt="Добавить физическое лицо" class='icon1'></a></div>
            <div class='tableButton'><a title="Списком" asp-action="Index" asp-controller="IndividualEntrepreneur"><img src='~/images/material/list.png' alt="Списком" class='icon1'></a></div>
        </div>

        <div class='search'>
            @using (Html.BeginForm())
            {
                <p>
                    @Html.TextBox("SearchString")
                    <button type="submit" title="Поиск" class="btn-link button-icon"><img src='~/images/material/search.png' alt="Поиск" class='searcherImg icon'></button>
                </p>
            }
        </div>
    </div>




    <div class='tableBlock ' style="width:95%">
        @foreach (var item in Model)
        {
            <div class='individualCardGray'>
                <p class='textInIndividualCards'><b>@Html.DisplayFor(modelItem => item.Fullname)</b></p>
                <span class='textInIndividualCards'>ИНН:</span>
                <span class='textInIndividualCards'>@Html.DisplayFor(modelItem => item.Inn)</span>
                <br />
                <span class='textInIndividualCards'>Адрес:</span>
                <span class='textInIndividualCards'>@Html.DisplayFor(modelItem => item.Address)</span>
                <br />
                <div class='menuForIndividuslCards'>
                    <a asp-action="Edit" asp-controller="IndividualEntrepreneur" asp-route-id="@item.Id" title="Изменить"><img src='~/images/material/edit.png' alt="Изменить" class='icon3'></a>
                    <a asp-action="Details" asp-controller="IndividualEntrepreneur" asp-route-id="@item.Id" title="Подробнее"><img src='~/images/material/more.png' alt="Подробнее" class='icon3'></a>
                    @if (User.Claims.FirstOrDefault(c => c.Value == "Admin") != null)
                    {
                        if (item.IsBlocked)
                        {
                            <button asp-action="unBlock" asp-controller="IndividualEntrepreneur" asp-route-id="@item.Id" style="position:relative; top:0px; padding:0px;" type="submit" class="btn-link button-icon blockUnlockBtn" title="Разблокировать"><img src='~/images/material/lock.png' alt="Разблокировать" class='icon3'></button>
                        }
                        else
                        {
                            <button asp-action="Block" asp-controller="IndividualEntrepreneur" asp-route-id="@item.Id" style="position:relative; top:0px; padding:0px;" type="submit" class="btn-link button-icon blockUnlockBtn" title="Заблокировать"><img src='~/images/material/unlock.png' alt="Заблокировать" class='icon3'></button>
                        }
                    }
                </div>
            </div>
        }
    </div>
</div>

CAStest/Views/IndividualEntrepreneur/Create.cshtml
@model CAStest.Models.IndividualEntrepreneurViewModels.CreateIEViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a asp-action="Index" asp-controller="IndividualEntrepreneur" title="Назад" style="position:relative; top:25px"><img src='~/images/material/back.png' alt="Назад" class='icon2'></a>
<br />

<h2>Индивидуальный предприниматель</h2>

<h4>Создание индивидуального предпренимателя</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fullname" class="control-label">ФИО</label>
                <br />
                <input asp-for="Fullname" id="registerInput" />
                <span asp-validation-for="Fullname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inn" class="control-label">ИНН</label>
                <br />
                <input asp-for="Inn" id="registerInput" />
                <span asp-validation-for="Inn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Дата рождения</label>
                <br />
                <input asp-for="DateOfBirth" id="registerInput" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportData" class="control-label">Паспортные данные</label>
                <br />
                <input asp-for="PassportData" id="registerInput" />
                <span asp-validation-for="PassportData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Countries" class="control-label selectCountries">Страна</label>
                <br />
                <select id="registerInput" asp-for="Country" asp-items="@Model.Countries">
                    <option selected="selected" value="@null">Выбрать страну</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Физический Адрес</label>
                <br />
                <input asp-for="Address" id="registerInput" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegalAddress" class="control-label">Юридический Адрес</label>
                <br />
                <input asp-for="LegalAddress" id="registerInput" />
                <span asp-validation-for="LegalAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Countries" class="control-label">Страна</label>
                <br />
                <select id="registerInput" asp-for="Country" asp-items="@Model.Countries">
                    <option selected="selected" value="@null">Выбрать страну</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-default"  style="border:1px solid #CA0039; border-radius:0px; color:#CA0039 " />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CAStest/Views/IndividualEntrepreneur/Delete.cshtml
@model CAStest.Models.IndividualEntrepreneur

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите это удалить?</h3>
<div>
    <h4>Индивидуальный предпрениматель</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Inn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Inn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PassportData)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PassportData)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LegalAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LegalAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

CAStest/Views/IndividualEntrepreneur/Details.cshtml
@model CAStest.Models.IndividualEntrepreneurViewModels.DetailsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a asp-action="Index" asp-controller="IndividualEntrepreneur" title="Назад" style="position:relative; top:25px"><img src='~/images/material/back.png' alt="Назад" class='icon2'></a>
<br />

<h2>Индивидуальный предпрениматель</h2>

<div>
    <h4>Детальная информация об индивидуальном предпренимателе</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            ФИО
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.Fullname)
        </dd>
        <dt>
            ИНН
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.Inn)
        </dd>
        <dt>
            Дата рождения
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.DateOfBirth)
        </dd>
        <dt>
            Паспортные данные
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.PassportData)
        </dd>

        <dt>
            Страна
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.Country)
        </dd>
        <dt>
            Физический Адрес
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.Address)
        </dd>
        <dt>
            Юридический Адрес
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.LegalAddress)
        </dd>
        <dt>
            Компания
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndividualEntrepreneur.Company)
        </dd>
    </dl>
</div>

<h4>Контакты <a asp-action="Create" asp-controller="Contact" asp-route-userId="@Model.IndividualEntrepreneur.Id"><img src='~/images/material/add.png' alt="Добавить контакт" class='icon1'></a> </h4>

<table class='tableUserList'>
    <tr class='tableUserListTr'>
        <th class='tableUserListTh'>
            Название
        </th>
        <th class='tableUserListTh'>
            Контакт
        </th>
        <th class='tableUserListTh'>
            Управление
        </th>
    </tr>
    <tbody>
        @foreach (var item in Model.Contacts)
        {
            <tr class='tableUserListTr'>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(model => item.ContactType.Name)
                </td>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(model => item.Value)
                </td>
                <td class='tableUserListTd'>
                    <a asp-action="Edit" asp-route-id="@item.Id" title="Изменить"><img src='~/images/material/edit.png' alt="Изменить" class='icon3'></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" title="Удалить"><img src='~/images/material/delete.png' alt="Удалить" class='icon3'></a>
                </td>
            </tr>
        }
</table>

CAStest/Views/IndividualEntrepreneur/Edit.cshtml
@model CAStest.Models.IndividualEntrepreneur

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a asp-action="Index" asp-controller="IndividualEntrepreneur" title="Назад" style="position:relative; top:25px"><img src='~/images/material/back.png' alt="Назад" class='icon2'></a>
<br />

<h2>Индивидульныей предпрениматель</h2>

<h4>Изменение индивидуального предпренимателя</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fullname" class="control-label">ФИО</label>
                <br />
                <input asp-for="Fullname" id="registerInput" />
                <span asp-validation-for="Fullname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inn" class="control-label">ИНН</label>
                <br />
                <input asp-for="Inn" id="registerInput" />
                <span asp-validation-for="Inn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label">Дата рождения</label>
                <br />
                <input asp-for="DateOfBirth" id="registerInput" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportData" class="control-label">Паспортные данные</label>
                <br />
                <input asp-for="PassportData" id="registerInput" />
                <span asp-validation-for="PassportData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Физический Адрес</label>
                <br />
                <input asp-for="Address" id="registerInput" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LegalAddress" class="control-label">Юридический Адрес</label>
                <br />
                <input asp-for="LegalAddress" id="registerInput" />
                <span asp-validation-for="LegalAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label">Страна</label>
                <br />
                <select id="registerInput" asp-for="Country" asp-items="ViewBag.Country">
                    <option selected="selected" value="@null">@Model.Country</option>
                </select>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" style="border:1px solid #CA0039; border-radius:0px; color:#CA0039 " />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CAStest/Views/IndividualEntrepreneur/Index.cshtml
@model IEnumerable<CAStest.Models.IndividualEntrepreneur>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="color:#066023">Индивидуальные предпрениматели</h2>
<div class="controlPanel">
    <div class='addingButton'><a title="Добавить физическое лицо" asp-action="Create"><img src='~/images/material/add.png' alt="Добавить физическое лицо" class='icon1'></a></div>
    <div class='tableButton'><a title="Карточками" asp-action="Cards" asp-controller="IndividualEntrepreneur"><img src='~/images/material/cards.png' alt="Карточками" class='icon1'></a></div>
    <div class='search'>
        @using (Html.BeginForm())
        {
            <p>
                @Html.TextBox("SearchString")
                <button type="submit" title="Поиск" class="btn-link button-icon"><img src='~/images/material/search.png' alt="Поиск" class='searcherImg icon'></button>
            </p>
        }
    </div>
</div>
<div class='tableBlock ' style="width:95%">
    <table class='tableUserList'>
        <tr class='tableUserListTr'>
            <th class='tableUserListTh'>@Html.ActionLink("Полное имя", "Index", new { sortOrder = ViewBag.NameSortParm })</th>
            <th class='tableUserListTh'>
                ИНН
            </th>
            <th class='tableUserListTh'>
                Дата
            </th>
            <th class='tableUserListTh'>
                Паспортные данные
            </th>
            <th class='tableUserListTh'>
                Физический Адрес
            </th>
            <th class='tableUserListTh'>
                Юридический Адрес
            </th>
            <th class='tableUserListTh'>
                Управление
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr class='tableUserListTr'>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(modelItem => item.Fullname)
                </td>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(modelItem => item.Inn)
                </td>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(modelItem => item.PassportData)
                </td>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td class='tableUserListTd'>
                    @Html.DisplayFor(modelItem => item.LegalAddress)
                </td>
                <td class='tableUserListTd'>
                    <a asp-action="Edit" asp-route-id="@item.Id" title="Изменить"><img src='~/images/material/edit.png' alt="Изменить" class='icon3'></a>
                    <a asp-action="Details" asp-route-id="@item.Id" title="Подробнее"><img src='~/images/material/description.png' alt="Подробнее" class='icon3'></a>

                    @if (User.Claims.FirstOrDefault(c => c.Value == "Admin") != null)
                    {
                        if (item.IsBlocked)
                        {
                            <form asp-action="unBlock" asp-controller="IndividualEntrepreneur" asp-route-id="@item.Id">
                                <button  style="position:relative; top:0px; padding:0px;" type="submit" class="btn-link button-icon blockUnlockBtn" title="Разблокировать"><img src='~/images/material/lock.png' alt="Разблокировать" class='icon3'></button>
                            </form>
                            
                        }
                        else
                        {
                            <form asp-action="Block" asp-controller="IndividualEntrepreneur" asp-route-id="@item.Id">
                                <button  style="position:relative; top:0px; padding:0px;" type="submit" class="btn-link button-icon blockUnlockBtn" title="Заблокировать"><img src='~/images/material/unlock.png' alt="Заблокировать" class='icon3'></button>
                            </form>
                            
                        }
                    }
                </td>
            </tr>
        }
    </table>
</div>